## Deliverable 3. Create a Travel Itinerary Map.

In [81]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy
# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [82]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Manaure,CO,79.52,overcast clouds,11.7751,-72.4445,Hotel Palaaima
1,2,Namibe,AO,68.63,clear sky,-15.1961,12.1522,Hotel Chik Chik Namibe
2,3,Nelson Bay,AU,60.01,broken clouds,-32.7167,152.1500,Mantra Nelson Bay
3,4,Atuona,PF,78.24,scattered clouds,-9.8000,-139.0333,Villa Enata
4,5,Qui Nhon,VN,81.95,overcast clouds,13.7667,109.2333,Khách sạn Hải Âu Quy Nhơn - Seagull Hotel
5,6,Gizo,SB,82.76,broken clouds,-8.1030,156.8419,Imagination Island
6,10,Coolum Beach,AU,65.10,light rain,-26.5333,153.1000,Coolum Beach Resort
7,15,Santa Lucia,ES,65.52,scattered clouds,27.9117,-15.5407,Las Tirajanas
8,16,Rikitea,PF,75.42,light rain,-23.1203,-134.9692,People ThankYou
9,17,Georgetown,MY,89.55,few clouds,5.4112,100.3354,Cititel Penang
10,19,Fare,PF,80.80,clear sky,-16.7000,-151.0167,Maitai Lapita Village Huahine
11,21,Nicoya,CR,75.47,overcast clouds,10.1483,-85.4520,Las Cabinas Del Sueño
12,23,Suez,EG,89.56,clear sky,29.9737,32.5263,Green House
13,24,Camopi,GF,73.63,overcast clouds,3.1655,-52.3158,La pousada
14,25,Baculin,PH,79.74,overcast clouds,7.4525,126.5842,Baculin Cove Beach Resort
15,29,Vanimo,PG,79.39,broken clouds,-2.6741,141.3028,Vahmoneh Lodge Vanimo
16,30,Gondanglegi,ID,79.03,broken clouds,-7.7479,112.0132,pondok pesantren mamba'ul 'ulum selo rejo
17,31,Stara Synyava,UA,63.07,clear sky,49.6032,27.6191,Готель Стара Синява LEX
18,33,Carnarvon,AU,70.75,broken clouds,-24.8667,113.6333,Hospitality Carnarvon
19,38,Zahesi,GE,65.91,scattered clouds,41.8246,44.7536,Sanapiro
20,39,Alyangula,AU,77.23,broken clouds,-13.8483,136.4192,Groote Eylandt Lodge
21,40,Jiuquan,CN,86.99,overcast clouds,39.7432,98.5174,Jiuquan Hotel
22,41,Taksimo,RU,62.53,overcast clouds,56.3444,114.8794,"Gostinitsa ""Domashniy Ochag"""
23,42,Auki,SB,77.77,broken clouds,-8.7676,160.7034,Auki Motel
24,43,Mocuba,MZ,76.66,broken clouds,-16.8392,36.9856,Phama Lodge
25,46,Dillon,US,71.94,overcast clouds,34.4166,-79.3712,Dillon Express Inn
26,47,Busselton,AU,62.92,broken clouds,-33.6500,115.3333,Observatory Guest House

In [83]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}<dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [84]:
# Configure gmaps to use your Google API key.
# fig = gmaps.figure(center=(30.0, 31.0), zoom_level= 1.5)
gmaps.configure(api_key=g_key)

# Assign the figure variable.
fig = gmaps.figure()

In [85]:
# 4a. Add a marker layer for each city to the map.
markers_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# 4b. Display the figure
fig.add_layer(markers_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [92]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.
city_start = "Busselton"
city_end = "Busselton"
stop1 = "Coolum Beach"
stop2 = "Nelson Bay"
stop3 = "Carnarvon"

vacation_start = vacation_df.loc[vacation_df["City"] == city_start]
vacation_end = vacation_df.loc[vacation_df["City"] == city_start]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == stop1]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == stop2] 
vacation_stop3 = vacation_df.loc[vacation_df["City"] == stop3]

In [95]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]].to_numpy()[0]
end = vacation_start[["Lat", "Lng"]].to_numpy()[0]
city_stop1 = vacation_stop1[["Lat", "Lng"]].to_numpy()[0]
city_stop2 = vacation_stop2[["Lat", "Lng"]].to_numpy()[0]
city_stop3 = vacation_stop3[["Lat", "Lng"]].to_numpy()[0]

In [96]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

fig = gmaps.figure()
vacation_route = gmaps.directions_layer(start, end, waypoints=[city_stop1,city_stop2,city_stop3], travel_mode="DRIVING" or "BICYCLING" or "WALKING")
fig.add_layer(vacation_route)
fig

Figure(layout=FigureLayout(height='420px'))

In [99]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3], ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,47,Busselton,AU,62.92,broken clouds,-33.6500,115.3333,Observatory Guest House
1,10,Coolum Beach,AU,65.10,light rain,-26.5333,153.1000,Coolum Beach Resort
2,3,Nelson Bay,AU,60.01,broken clouds,-32.7167,152.1500,Mantra Nelson Bay
3,33,Carnarvon,AU,70.75,broken clouds,-24.8667,113.6333,Hospitality Carnarvon

In [100]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [101]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))